export const metadata = {
  title: 'DHB Courses',
  description: 'Generated by Next.js',
}
 
export default function Rootayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
