'use client'



import Context from "./context/context"


export const metadata = {
  title: 'DHB Courses',
  description: 'Generated by Next.js',
}
 




export default function Rootayout({ children }) {





 return (
    <html lang="en">
      <body>
      <Context>
        {children}
        </Context>
        </body>
    </html>
  )
}
